import { Outfit } from "next/font/google";

import "./globals.css";

const quickSand = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "TS Labs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`${quickSand.className} antialiased`}
      >
        
        {children}
      </body>
    </html>
  );
}
